sudo: false

language: node_js

node_js:
  - "8"
  - "node"

deploy:
  provider: heroku
  api_key:
    secure: process.env.HEROKU_AUTH
  app: goonies-barback
  on:
    repo: The-Goonies/barback

cache:
  directories:
    - "node_modules"
